name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up submodules
        run: bash ./scripts/addSubmodules.sh

      - name: Build with docker
        run: docker run --workdir "$GITHUB_WORKSPACE" --mount type=bind,source="$GITHUB_WORKSPACE",target="$GITHUB_WORKSPACE" --user "$(id -u)":"$(id -g)" gringofts/compile:v1 hooks/pre-commit

      - name: Upload test report to codecov
        run: bash <(curl -s https://codecov.io/bash)

  CppLint:
    runs-on: ubuntu-latest

    steps:
      - uses: CyberZHG/github-action-cpp-lint@master

  ShellCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: bewuethr/shellcheck-action@v1
